package com.example

val forcastJsonResponse = """
{
    "@context": [
        "https://geojson.org/geojson-ld/geojson-context.jsonld",
        {
            "@version": "1.1",
            "wx": "https://api.weather.gov/ontology#",
            "geo": "http://www.opengis.net/ont/geosparql#",
            "unit": "http://codes.wmo.int/common/unit/",
            "@vocab": "https://api.weather.gov/ontology#"
        }
    ],
    "type": "Feature",
    "geometry": {
        "type": "Polygon",
        "coordinates": [
            [
                [
                    -97.1089731,
                    39.766826299999998
                ],
                [
                    -97.108526900000001,
                    39.744778799999999
                ],
                [
                    -97.079846700000004,
                    39.745119500000001
                ],
                [
                    -97.08028680000001,
                    39.767167000000001
                ],
                [
                    -97.1089731,
                    39.766826299999998
                ]
            ]
        ]
    },
    "properties": {
        "updated": "2022-03-02T20:39:34+00:00",
        "units": "us",
        "forecastGenerator": "HourlyForecastGenerator",
        "generatedAt": "2022-03-02T22:51:57+00:00",
        "updateTime": "2022-03-02T20:39:34+00:00",
        "validTimes": "2022-03-02T14:00:00+00:00/P7DT11H",
        "elevation": {
            "unitCode": "wmoUnit:m",
            "value": 441.95999999999998
        },
        "periods": [
            {
                "number": 1,
                "name": "",
                "startTime": "2022-03-02T16:00:00-06:00",
                "endTime": "2022-03-02T17:00:00-06:00",
                "isDaytime": true,
                "temperature": 76,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "5 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/day/few?size=small",
                "shortForecast": "Sunny",
                "detailedForecast": ""
            },
            {
                "number": 2,
                "name": "",
                "startTime": "2022-03-02T17:00:00-06:00",
                "endTime": "2022-03-02T18:00:00-06:00",
                "isDaytime": true,
                "temperature": 77,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/day/few?size=small",
                "shortForecast": "Sunny",
                "detailedForecast": ""
            },
            {
                "number": 3,
                "name": "",
                "startTime": "2022-03-02T18:00:00-06:00",
                "endTime": "2022-03-02T19:00:00-06:00",
                "isDaytime": false,
                "temperature": 72,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "5 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/night/skc?size=small",
                "shortForecast": "Clear",
                "detailedForecast": ""
            },
            {
                "number": 4,
                "name": "",
                "startTime": "2022-03-02T19:00:00-06:00",
                "endTime": "2022-03-02T20:00:00-06:00",
                "isDaytime": false,
                "temperature": 67,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "5 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/night/skc?size=small",
                "shortForecast": "Clear",
                "detailedForecast": ""
            },
            {
                "number": 5,
                "name": "",
                "startTime": "2022-03-02T20:00:00-06:00",
                "endTime": "2022-03-02T21:00:00-06:00",
                "isDaytime": false,
                "temperature": 61,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "5 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/night/skc?size=small",
                "shortForecast": "Clear",
                "detailedForecast": ""
            },
            {
                "number": 6,
                "name": "",
                "startTime": "2022-03-02T21:00:00-06:00",
                "endTime": "2022-03-02T22:00:00-06:00",
                "isDaytime": false,
                "temperature": 56,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/night/skc?size=small",
                "shortForecast": "Clear",
                "detailedForecast": ""
            },
            {
                "number": 7,
                "name": "",
                "startTime": "2022-03-02T22:00:00-06:00",
                "endTime": "2022-03-02T23:00:00-06:00",
                "isDaytime": false,
                "temperature": 52,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/night/skc?size=small",
                "shortForecast": "Clear",
                "detailedForecast": ""
            },
            {
                "number": 8,
                "name": "",
                "startTime": "2022-03-02T23:00:00-06:00",
                "endTime": "2022-03-03T00:00:00-06:00",
                "isDaytime": false,
                "temperature": 50,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 9,
                "name": "",
                "startTime": "2022-03-03T00:00:00-06:00",
                "endTime": "2022-03-03T01:00:00-06:00",
                "isDaytime": false,
                "temperature": 48,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 10,
                "name": "",
                "startTime": "2022-03-03T01:00:00-06:00",
                "endTime": "2022-03-03T02:00:00-06:00",
                "isDaytime": false,
                "temperature": 46,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 11,
                "name": "",
                "startTime": "2022-03-03T02:00:00-06:00",
                "endTime": "2022-03-03T03:00:00-06:00",
                "isDaytime": false,
                "temperature": 43,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 12,
                "name": "",
                "startTime": "2022-03-03T03:00:00-06:00",
                "endTime": "2022-03-03T04:00:00-06:00",
                "isDaytime": false,
                "temperature": 41,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
                "shortForecast": "Partly Cloudy",
                "detailedForecast": ""
            },
            {
                "number": 13,
                "name": "",
                "startTime": "2022-03-03T04:00:00-06:00",
                "endTime": "2022-03-03T05:00:00-06:00",
                "isDaytime": false,
                "temperature": 39,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
                "shortForecast": "Partly Cloudy",
                "detailedForecast": ""
            },
            {
                "number": 14,
                "name": "",
                "startTime": "2022-03-03T05:00:00-06:00",
                "endTime": "2022-03-03T06:00:00-06:00",
                "isDaytime": false,
                "temperature": 37,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
                "shortForecast": "Partly Cloudy",
                "detailedForecast": ""
            },
            {
                "number": 15,
                "name": "",
                "startTime": "2022-03-03T06:00:00-06:00",
                "endTime": "2022-03-03T07:00:00-06:00",
                "isDaytime": true,
                "temperature": 35,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
                "shortForecast": "Partly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 16,
                "name": "",
                "startTime": "2022-03-03T07:00:00-06:00",
                "endTime": "2022-03-03T08:00:00-06:00",
                "isDaytime": true,
                "temperature": 34,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "NE",
                "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
                "shortForecast": "Partly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 17,
                "name": "",
                "startTime": "2022-03-03T08:00:00-06:00",
                "endTime": "2022-03-03T09:00:00-06:00",
                "isDaytime": true,
                "temperature": 34,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
                "shortForecast": "Partly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 18,
                "name": "",
                "startTime": "2022-03-03T09:00:00-06:00",
                "endTime": "2022-03-03T10:00:00-06:00",
                "isDaytime": true,
                "temperature": 35,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
                "shortForecast": "Partly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 19,
                "name": "",
                "startTime": "2022-03-03T10:00:00-06:00",
                "endTime": "2022-03-03T11:00:00-06:00",
                "isDaytime": true,
                "temperature": 38,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
                "shortForecast": "Mostly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 20,
                "name": "",
                "startTime": "2022-03-03T11:00:00-06:00",
                "endTime": "2022-03-03T12:00:00-06:00",
                "isDaytime": true,
                "temperature": 41,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
                "shortForecast": "Mostly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 21,
                "name": "",
                "startTime": "2022-03-03T12:00:00-06:00",
                "endTime": "2022-03-03T13:00:00-06:00",
                "isDaytime": true,
                "temperature": 45,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
                "shortForecast": "Mostly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 22,
                "name": "",
                "startTime": "2022-03-03T13:00:00-06:00",
                "endTime": "2022-03-03T14:00:00-06:00",
                "isDaytime": true,
                "temperature": 49,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
                "shortForecast": "Mostly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 23,
                "name": "",
                "startTime": "2022-03-03T14:00:00-06:00",
                "endTime": "2022-03-03T15:00:00-06:00",
                "isDaytime": true,
                "temperature": 52,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/day/few?size=small",
                "shortForecast": "Sunny",
                "detailedForecast": ""
            },
            {
                "number": 24,
                "name": "",
                "startTime": "2022-03-03T15:00:00-06:00",
                "endTime": "2022-03-03T16:00:00-06:00",
                "isDaytime": true,
                "temperature": 55,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/day/few?size=small",
                "shortForecast": "Sunny",
                "detailedForecast": ""
            },
            {
                "number": 25,
                "name": "",
                "startTime": "2022-03-03T16:00:00-06:00",
                "endTime": "2022-03-03T17:00:00-06:00",
                "isDaytime": true,
                "temperature": 56,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/day/few?size=small",
                "shortForecast": "Sunny",
                "detailedForecast": ""
            },
            {
                "number": 26,
                "name": "",
                "startTime": "2022-03-03T17:00:00-06:00",
                "endTime": "2022-03-03T18:00:00-06:00",
                "isDaytime": true,
                "temperature": 56,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/day/few?size=small",
                "shortForecast": "Sunny",
                "detailedForecast": ""
            },
            {
                "number": 27,
                "name": "",
                "startTime": "2022-03-03T18:00:00-06:00",
                "endTime": "2022-03-03T19:00:00-06:00",
                "isDaytime": false,
                "temperature": 54,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 28,
                "name": "",
                "startTime": "2022-03-03T19:00:00-06:00",
                "endTime": "2022-03-03T20:00:00-06:00",
                "isDaytime": false,
                "temperature": 50,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 29,
                "name": "",
                "startTime": "2022-03-03T20:00:00-06:00",
                "endTime": "2022-03-03T21:00:00-06:00",
                "isDaytime": false,
                "temperature": 47,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 30,
                "name": "",
                "startTime": "2022-03-03T21:00:00-06:00",
                "endTime": "2022-03-03T22:00:00-06:00",
                "isDaytime": false,
                "temperature": 43,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
                "shortForecast": "Partly Cloudy",
                "detailedForecast": ""
            },
            {
                "number": 31,
                "name": "",
                "startTime": "2022-03-03T22:00:00-06:00",
                "endTime": "2022-03-03T23:00:00-06:00",
                "isDaytime": false,
                "temperature": 41,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
                "shortForecast": "Partly Cloudy",
                "detailedForecast": ""
            },
            {
                "number": 32,
                "name": "",
                "startTime": "2022-03-03T23:00:00-06:00",
                "endTime": "2022-03-04T00:00:00-06:00",
                "isDaytime": false,
                "temperature": 40,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
                "shortForecast": "Partly Cloudy",
                "detailedForecast": ""
            },
            {
                "number": 33,
                "name": "",
                "startTime": "2022-03-04T00:00:00-06:00",
                "endTime": "2022-03-04T01:00:00-06:00",
                "isDaytime": false,
                "temperature": 39,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
                "shortForecast": "Mostly Cloudy",
                "detailedForecast": ""
            },
            {
                "number": 34,
                "name": "",
                "startTime": "2022-03-04T01:00:00-06:00",
                "endTime": "2022-03-04T02:00:00-06:00",
                "isDaytime": false,
                "temperature": 39,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
                "shortForecast": "Mostly Cloudy",
                "detailedForecast": ""
            },
            {
                "number": 35,
                "name": "",
                "startTime": "2022-03-04T02:00:00-06:00",
                "endTime": "2022-03-04T03:00:00-06:00",
                "isDaytime": false,
                "temperature": 38,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "E",
                "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
                "shortForecast": "Mostly Cloudy",
                "detailedForecast": ""
            },
            {
                "number": 36,
                "name": "",
                "startTime": "2022-03-04T03:00:00-06:00",
                "endTime": "2022-03-04T04:00:00-06:00",
                "isDaytime": false,
                "temperature": 38,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "SE",
                "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
                "shortForecast": "Mostly Cloudy",
                "detailedForecast": ""
            },
            {
                "number": 37,
                "name": "",
                "startTime": "2022-03-04T04:00:00-06:00",
                "endTime": "2022-03-04T05:00:00-06:00",
                "isDaytime": false,
                "temperature": 38,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "SE",
                "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
                "shortForecast": "Mostly Cloudy",
                "detailedForecast": ""
            },
            {
                "number": 38,
                "name": "",
                "startTime": "2022-03-04T05:00:00-06:00",
                "endTime": "2022-03-04T06:00:00-06:00",
                "isDaytime": false,
                "temperature": 38,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "SE",
                "icon": "https://api.weather.gov/icons/land/night/bkn?size=small",
                "shortForecast": "Mostly Cloudy",
                "detailedForecast": ""
            },
            {
                "number": 39,
                "name": "",
                "startTime": "2022-03-04T06:00:00-06:00",
                "endTime": "2022-03-04T07:00:00-06:00",
                "isDaytime": true,
                "temperature": 40,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "SE",
                "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
                "shortForecast": "Partly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 40,
                "name": "",
                "startTime": "2022-03-04T07:00:00-06:00",
                "endTime": "2022-03-04T08:00:00-06:00",
                "isDaytime": true,
                "temperature": 42,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "SE",
                "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
                "shortForecast": "Partly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 41,
                "name": "",
                "startTime": "2022-03-04T08:00:00-06:00",
                "endTime": "2022-03-04T09:00:00-06:00",
                "isDaytime": true,
                "temperature": 45,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
                "shortForecast": "Partly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 42,
                "name": "",
                "startTime": "2022-03-04T09:00:00-06:00",
                "endTime": "2022-03-04T10:00:00-06:00",
                "isDaytime": true,
                "temperature": 49,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
                "shortForecast": "Partly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 43,
                "name": "",
                "startTime": "2022-03-04T10:00:00-06:00",
                "endTime": "2022-03-04T11:00:00-06:00",
                "isDaytime": true,
                "temperature": 55,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
                "shortForecast": "Partly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 44,
                "name": "",
                "startTime": "2022-03-04T11:00:00-06:00",
                "endTime": "2022-03-04T12:00:00-06:00",
                "isDaytime": true,
                "temperature": 61,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
                "shortForecast": "Partly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 45,
                "name": "",
                "startTime": "2022-03-04T12:00:00-06:00",
                "endTime": "2022-03-04T13:00:00-06:00",
                "isDaytime": true,
                "temperature": 66,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
                "shortForecast": "Partly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 46,
                "name": "",
                "startTime": "2022-03-04T13:00:00-06:00",
                "endTime": "2022-03-04T14:00:00-06:00",
                "isDaytime": true,
                "temperature": 70,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
                "shortForecast": "Mostly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 47,
                "name": "",
                "startTime": "2022-03-04T14:00:00-06:00",
                "endTime": "2022-03-04T15:00:00-06:00",
                "isDaytime": true,
                "temperature": 72,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
                "shortForecast": "Mostly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 48,
                "name": "",
                "startTime": "2022-03-04T15:00:00-06:00",
                "endTime": "2022-03-04T16:00:00-06:00",
                "isDaytime": true,
                "temperature": 73,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
                "shortForecast": "Mostly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 49,
                "name": "",
                "startTime": "2022-03-04T16:00:00-06:00",
                "endTime": "2022-03-04T17:00:00-06:00",
                "isDaytime": true,
                "temperature": 73,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
                "shortForecast": "Mostly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 50,
                "name": "",
                "startTime": "2022-03-04T17:00:00-06:00",
                "endTime": "2022-03-04T18:00:00-06:00",
                "isDaytime": true,
                "temperature": 72,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
                "shortForecast": "Mostly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 51,
                "name": "",
                "startTime": "2022-03-04T18:00:00-06:00",
                "endTime": "2022-03-04T19:00:00-06:00",
                "isDaytime": false,
                "temperature": 70,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
                "shortForecast": "Partly Cloudy",
                "detailedForecast": ""
            },
            {
                "number": 52,
                "name": "",
                "startTime": "2022-03-04T19:00:00-06:00",
                "endTime": "2022-03-04T20:00:00-06:00",
                "isDaytime": false,
                "temperature": 68,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
                "shortForecast": "Partly Cloudy",
                "detailedForecast": ""
            },
            {
                "number": 53,
                "name": "",
                "startTime": "2022-03-04T20:00:00-06:00",
                "endTime": "2022-03-04T21:00:00-06:00",
                "isDaytime": false,
                "temperature": 65,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
                "shortForecast": "Partly Cloudy",
                "detailedForecast": ""
            },
            {
                "number": 54,
                "name": "",
                "startTime": "2022-03-04T21:00:00-06:00",
                "endTime": "2022-03-04T22:00:00-06:00",
                "isDaytime": false,
                "temperature": 63,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
                "shortForecast": "Partly Cloudy",
                "detailedForecast": ""
            },
            {
                "number": 55,
                "name": "",
                "startTime": "2022-03-04T22:00:00-06:00",
                "endTime": "2022-03-04T23:00:00-06:00",
                "isDaytime": false,
                "temperature": 61,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
                "shortForecast": "Partly Cloudy",
                "detailedForecast": ""
            },
            {
                "number": 56,
                "name": "",
                "startTime": "2022-03-04T23:00:00-06:00",
                "endTime": "2022-03-05T00:00:00-06:00",
                "isDaytime": false,
                "temperature": 60,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
                "shortForecast": "Partly Cloudy",
                "detailedForecast": ""
            },
            {
                "number": 57,
                "name": "",
                "startTime": "2022-03-05T00:00:00-06:00",
                "endTime": "2022-03-05T01:00:00-06:00",
                "isDaytime": false,
                "temperature": 59,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/night/rain_showers?size=small",
                "shortForecast": "Chance Rain Showers",
                "detailedForecast": ""
            },
            {
                "number": 58,
                "name": "",
                "startTime": "2022-03-05T01:00:00-06:00",
                "endTime": "2022-03-05T02:00:00-06:00",
                "isDaytime": false,
                "temperature": 58,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/night/rain_showers?size=small",
                "shortForecast": "Chance Rain Showers",
                "detailedForecast": ""
            },
            {
                "number": 59,
                "name": "",
                "startTime": "2022-03-05T02:00:00-06:00",
                "endTime": "2022-03-05T03:00:00-06:00",
                "isDaytime": false,
                "temperature": 58,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/night/rain_showers?size=small",
                "shortForecast": "Chance Rain Showers",
                "detailedForecast": ""
            },
            {
                "number": 60,
                "name": "",
                "startTime": "2022-03-05T03:00:00-06:00",
                "endTime": "2022-03-05T04:00:00-06:00",
                "isDaytime": false,
                "temperature": 57,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/night/rain_showers?size=small",
                "shortForecast": "Chance Rain Showers",
                "detailedForecast": ""
            },
            {
                "number": 61,
                "name": "",
                "startTime": "2022-03-05T04:00:00-06:00",
                "endTime": "2022-03-05T05:00:00-06:00",
                "isDaytime": false,
                "temperature": 56,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/night/rain_showers?size=small",
                "shortForecast": "Chance Rain Showers",
                "detailedForecast": ""
            },
            {
                "number": 62,
                "name": "",
                "startTime": "2022-03-05T05:00:00-06:00",
                "endTime": "2022-03-05T06:00:00-06:00",
                "isDaytime": false,
                "temperature": 55,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/night/rain_showers?size=small",
                "shortForecast": "Chance Rain Showers",
                "detailedForecast": ""
            },
            {
                "number": 63,
                "name": "",
                "startTime": "2022-03-05T06:00:00-06:00",
                "endTime": "2022-03-05T07:00:00-06:00",
                "isDaytime": true,
                "temperature": 54,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
                "shortForecast": "Chance Rain Showers",
                "detailedForecast": ""
            },
            {
                "number": 64,
                "name": "",
                "startTime": "2022-03-05T07:00:00-06:00",
                "endTime": "2022-03-05T08:00:00-06:00",
                "isDaytime": true,
                "temperature": 54,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
                "shortForecast": "Chance Rain Showers",
                "detailedForecast": ""
            },
            {
                "number": 65,
                "name": "",
                "startTime": "2022-03-05T08:00:00-06:00",
                "endTime": "2022-03-05T09:00:00-06:00",
                "isDaytime": true,
                "temperature": 55,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
                "shortForecast": "Chance Rain Showers",
                "detailedForecast": ""
            },
            {
                "number": 66,
                "name": "",
                "startTime": "2022-03-05T09:00:00-06:00",
                "endTime": "2022-03-05T10:00:00-06:00",
                "isDaytime": true,
                "temperature": 57,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
                "shortForecast": "Chance Rain Showers",
                "detailedForecast": ""
            },
            {
                "number": 67,
                "name": "",
                "startTime": "2022-03-05T10:00:00-06:00",
                "endTime": "2022-03-05T11:00:00-06:00",
                "isDaytime": true,
                "temperature": 60,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
                "shortForecast": "Chance Rain Showers",
                "detailedForecast": ""
            },
            {
                "number": 68,
                "name": "",
                "startTime": "2022-03-05T11:00:00-06:00",
                "endTime": "2022-03-05T12:00:00-06:00",
                "isDaytime": true,
                "temperature": 63,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
                "shortForecast": "Chance Rain Showers",
                "detailedForecast": ""
            },
            {
                "number": 69,
                "name": "",
                "startTime": "2022-03-05T12:00:00-06:00",
                "endTime": "2022-03-05T13:00:00-06:00",
                "isDaytime": true,
                "temperature": 66,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "S",
                "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
                "shortForecast": "Chance Rain Showers",
                "detailedForecast": ""
            },
            {
                "number": 70,
                "name": "",
                "startTime": "2022-03-05T13:00:00-06:00",
                "endTime": "2022-03-05T14:00:00-06:00",
                "isDaytime": true,
                "temperature": 68,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "SW",
                "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
                "shortForecast": "Chance Rain Showers",
                "detailedForecast": ""
            },
            {
                "number": 71,
                "name": "",
                "startTime": "2022-03-05T14:00:00-06:00",
                "endTime": "2022-03-05T15:00:00-06:00",
                "isDaytime": true,
                "temperature": 69,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "SW",
                "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
                "shortForecast": "Chance Rain Showers",
                "detailedForecast": ""
            },
            {
                "number": 72,
                "name": "",
                "startTime": "2022-03-05T15:00:00-06:00",
                "endTime": "2022-03-05T16:00:00-06:00",
                "isDaytime": true,
                "temperature": 68,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "SW",
                "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
                "shortForecast": "Chance Rain Showers",
                "detailedForecast": ""
            },
            {
                "number": 73,
                "name": "",
                "startTime": "2022-03-05T16:00:00-06:00",
                "endTime": "2022-03-05T17:00:00-06:00",
                "isDaytime": true,
                "temperature": 66,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "SW",
                "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
                "shortForecast": "Chance Rain Showers",
                "detailedForecast": ""
            },
            {
                "number": 74,
                "name": "",
                "startTime": "2022-03-05T17:00:00-06:00",
                "endTime": "2022-03-05T18:00:00-06:00",
                "isDaytime": true,
                "temperature": 62,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "W",
                "icon": "https://api.weather.gov/icons/land/day/rain_showers?size=small",
                "shortForecast": "Chance Rain Showers",
                "detailedForecast": ""
            },
            {
                "number": 75,
                "name": "",
                "startTime": "2022-03-05T18:00:00-06:00",
                "endTime": "2022-03-05T19:00:00-06:00",
                "isDaytime": false,
                "temperature": 58,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "W",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 76,
                "name": "",
                "startTime": "2022-03-05T19:00:00-06:00",
                "endTime": "2022-03-05T20:00:00-06:00",
                "isDaytime": false,
                "temperature": 53,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "W",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 77,
                "name": "",
                "startTime": "2022-03-05T20:00:00-06:00",
                "endTime": "2022-03-05T21:00:00-06:00",
                "isDaytime": false,
                "temperature": 48,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "W",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 78,
                "name": "",
                "startTime": "2022-03-05T21:00:00-06:00",
                "endTime": "2022-03-05T22:00:00-06:00",
                "isDaytime": false,
                "temperature": 43,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "NW",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 79,
                "name": "",
                "startTime": "2022-03-05T22:00:00-06:00",
                "endTime": "2022-03-05T23:00:00-06:00",
                "isDaytime": false,
                "temperature": 40,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "NW",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 80,
                "name": "",
                "startTime": "2022-03-05T23:00:00-06:00",
                "endTime": "2022-03-06T00:00:00-06:00",
                "isDaytime": false,
                "temperature": 38,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "NW",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 81,
                "name": "",
                "startTime": "2022-03-06T00:00:00-06:00",
                "endTime": "2022-03-06T01:00:00-06:00",
                "isDaytime": false,
                "temperature": 36,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "20 mph",
                "windDirection": "NW",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 82,
                "name": "",
                "startTime": "2022-03-06T01:00:00-06:00",
                "endTime": "2022-03-06T02:00:00-06:00",
                "isDaytime": false,
                "temperature": 34,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "NW",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 83,
                "name": "",
                "startTime": "2022-03-06T02:00:00-06:00",
                "endTime": "2022-03-06T03:00:00-06:00",
                "isDaytime": false,
                "temperature": 33,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "NW",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 84,
                "name": "",
                "startTime": "2022-03-06T03:00:00-06:00",
                "endTime": "2022-03-06T04:00:00-06:00",
                "isDaytime": false,
                "temperature": 32,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "NW",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 85,
                "name": "",
                "startTime": "2022-03-06T04:00:00-06:00",
                "endTime": "2022-03-06T05:00:00-06:00",
                "isDaytime": false,
                "temperature": 30,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "NW",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 86,
                "name": "",
                "startTime": "2022-03-06T05:00:00-06:00",
                "endTime": "2022-03-06T06:00:00-06:00",
                "isDaytime": false,
                "temperature": 29,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 87,
                "name": "",
                "startTime": "2022-03-06T06:00:00-06:00",
                "endTime": "2022-03-06T07:00:00-06:00",
                "isDaytime": true,
                "temperature": 28,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/few?size=small",
                "shortForecast": "Sunny",
                "detailedForecast": ""
            },
            {
                "number": 88,
                "name": "",
                "startTime": "2022-03-06T07:00:00-06:00",
                "endTime": "2022-03-06T08:00:00-06:00",
                "isDaytime": true,
                "temperature": 28,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/few?size=small",
                "shortForecast": "Sunny",
                "detailedForecast": ""
            },
            {
                "number": 89,
                "name": "",
                "startTime": "2022-03-06T08:00:00-06:00",
                "endTime": "2022-03-06T09:00:00-06:00",
                "isDaytime": true,
                "temperature": 28,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/few?size=small",
                "shortForecast": "Sunny",
                "detailedForecast": ""
            },
            {
                "number": 90,
                "name": "",
                "startTime": "2022-03-06T09:00:00-06:00",
                "endTime": "2022-03-06T10:00:00-06:00",
                "isDaytime": true,
                "temperature": 29,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/few?size=small",
                "shortForecast": "Sunny",
                "detailedForecast": ""
            },
            {
                "number": 91,
                "name": "",
                "startTime": "2022-03-06T10:00:00-06:00",
                "endTime": "2022-03-06T11:00:00-06:00",
                "isDaytime": true,
                "temperature": 32,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
                "shortForecast": "Mostly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 92,
                "name": "",
                "startTime": "2022-03-06T11:00:00-06:00",
                "endTime": "2022-03-06T12:00:00-06:00",
                "isDaytime": true,
                "temperature": 35,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
                "shortForecast": "Mostly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 93,
                "name": "",
                "startTime": "2022-03-06T12:00:00-06:00",
                "endTime": "2022-03-06T13:00:00-06:00",
                "isDaytime": true,
                "temperature": 38,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
                "shortForecast": "Mostly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 94,
                "name": "",
                "startTime": "2022-03-06T13:00:00-06:00",
                "endTime": "2022-03-06T14:00:00-06:00",
                "isDaytime": true,
                "temperature": 40,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
                "shortForecast": "Mostly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 95,
                "name": "",
                "startTime": "2022-03-06T14:00:00-06:00",
                "endTime": "2022-03-06T15:00:00-06:00",
                "isDaytime": true,
                "temperature": 42,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
                "shortForecast": "Mostly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 96,
                "name": "",
                "startTime": "2022-03-06T15:00:00-06:00",
                "endTime": "2022-03-06T16:00:00-06:00",
                "isDaytime": true,
                "temperature": 43,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/bkn?size=small",
                "shortForecast": "Partly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 97,
                "name": "",
                "startTime": "2022-03-06T16:00:00-06:00",
                "endTime": "2022-03-06T17:00:00-06:00",
                "isDaytime": true,
                "temperature": 43,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
                "shortForecast": "Mostly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 98,
                "name": "",
                "startTime": "2022-03-06T17:00:00-06:00",
                "endTime": "2022-03-06T18:00:00-06:00",
                "isDaytime": true,
                "temperature": 43,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/sct?size=small",
                "shortForecast": "Mostly Sunny",
                "detailedForecast": ""
            },
            {
                "number": 99,
                "name": "",
                "startTime": "2022-03-06T18:00:00-06:00",
                "endTime": "2022-03-06T19:00:00-06:00",
                "isDaytime": false,
                "temperature": 41,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/night/rain?size=small",
                "shortForecast": "Chance Light Rain",
                "detailedForecast": ""
            },
            {
                "number": 100,
                "name": "",
                "startTime": "2022-03-06T19:00:00-06:00",
                "endTime": "2022-03-06T20:00:00-06:00",
                "isDaytime": false,
                "temperature": 39,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/night/rain?size=small",
                "shortForecast": "Chance Light Rain",
                "detailedForecast": ""
            },
            {
                "number": 101,
                "name": "",
                "startTime": "2022-03-06T20:00:00-06:00",
                "endTime": "2022-03-06T21:00:00-06:00",
                "isDaytime": false,
                "temperature": 36,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/night/snow?size=small",
                "shortForecast": "Chance Rain And Snow",
                "detailedForecast": ""
            },
            {
                "number": 102,
                "name": "",
                "startTime": "2022-03-06T21:00:00-06:00",
                "endTime": "2022-03-06T22:00:00-06:00",
                "isDaytime": false,
                "temperature": 33,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/night/snow?size=small",
                "shortForecast": "Chance Light Snow",
                "detailedForecast": ""
            },
            {
                "number": 103,
                "name": "",
                "startTime": "2022-03-06T22:00:00-06:00",
                "endTime": "2022-03-06T23:00:00-06:00",
                "isDaytime": false,
                "temperature": 32,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/night/snow?size=small",
                "shortForecast": "Chance Light Snow",
                "detailedForecast": ""
            },
            {
                "number": 104,
                "name": "",
                "startTime": "2022-03-06T23:00:00-06:00",
                "endTime": "2022-03-07T00:00:00-06:00",
                "isDaytime": false,
                "temperature": 31,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/night/snow?size=small",
                "shortForecast": "Chance Light Snow",
                "detailedForecast": ""
            },
            {
                "number": 105,
                "name": "",
                "startTime": "2022-03-07T00:00:00-06:00",
                "endTime": "2022-03-07T01:00:00-06:00",
                "isDaytime": false,
                "temperature": 30,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/night/snow?size=small",
                "shortForecast": "Chance Light Snow",
                "detailedForecast": ""
            },
            {
                "number": 106,
                "name": "",
                "startTime": "2022-03-07T01:00:00-06:00",
                "endTime": "2022-03-07T02:00:00-06:00",
                "isDaytime": false,
                "temperature": 29,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/night/snow?size=small",
                "shortForecast": "Chance Light Snow",
                "detailedForecast": ""
            },
            {
                "number": 107,
                "name": "",
                "startTime": "2022-03-07T02:00:00-06:00",
                "endTime": "2022-03-07T03:00:00-06:00",
                "isDaytime": false,
                "temperature": 28,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/night/snow?size=small",
                "shortForecast": "Chance Light Snow",
                "detailedForecast": ""
            },
            {
                "number": 108,
                "name": "",
                "startTime": "2022-03-07T03:00:00-06:00",
                "endTime": "2022-03-07T04:00:00-06:00",
                "isDaytime": false,
                "temperature": 27,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/night/snow?size=small",
                "shortForecast": "Chance Light Snow",
                "detailedForecast": ""
            },
            {
                "number": 109,
                "name": "",
                "startTime": "2022-03-07T04:00:00-06:00",
                "endTime": "2022-03-07T05:00:00-06:00",
                "isDaytime": false,
                "temperature": 26,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/night/snow?size=small",
                "shortForecast": "Chance Light Snow",
                "detailedForecast": ""
            },
            {
                "number": 110,
                "name": "",
                "startTime": "2022-03-07T05:00:00-06:00",
                "endTime": "2022-03-07T06:00:00-06:00",
                "isDaytime": false,
                "temperature": 25,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/night/snow?size=small",
                "shortForecast": "Chance Light Snow",
                "detailedForecast": ""
            },
            {
                "number": 111,
                "name": "",
                "startTime": "2022-03-07T06:00:00-06:00",
                "endTime": "2022-03-07T07:00:00-06:00",
                "isDaytime": true,
                "temperature": 24,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/snow?size=small",
                "shortForecast": "Chance Light Snow",
                "detailedForecast": ""
            },
            {
                "number": 112,
                "name": "",
                "startTime": "2022-03-07T07:00:00-06:00",
                "endTime": "2022-03-07T08:00:00-06:00",
                "isDaytime": true,
                "temperature": 23,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/snow?size=small",
                "shortForecast": "Chance Light Snow",
                "detailedForecast": ""
            },
            {
                "number": 113,
                "name": "",
                "startTime": "2022-03-07T08:00:00-06:00",
                "endTime": "2022-03-07T09:00:00-06:00",
                "isDaytime": true,
                "temperature": 23,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/snow?size=small",
                "shortForecast": "Chance Light Snow",
                "detailedForecast": ""
            },
            {
                "number": 114,
                "name": "",
                "startTime": "2022-03-07T09:00:00-06:00",
                "endTime": "2022-03-07T10:00:00-06:00",
                "isDaytime": true,
                "temperature": 24,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/snow?size=small",
                "shortForecast": "Chance Light Snow",
                "detailedForecast": ""
            },
            {
                "number": 115,
                "name": "",
                "startTime": "2022-03-07T10:00:00-06:00",
                "endTime": "2022-03-07T11:00:00-06:00",
                "isDaytime": true,
                "temperature": 26,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/snow?size=small",
                "shortForecast": "Chance Light Snow",
                "detailedForecast": ""
            },
            {
                "number": 116,
                "name": "",
                "startTime": "2022-03-07T11:00:00-06:00",
                "endTime": "2022-03-07T12:00:00-06:00",
                "isDaytime": true,
                "temperature": 29,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/snow?size=small",
                "shortForecast": "Chance Light Snow",
                "detailedForecast": ""
            },
            {
                "number": 117,
                "name": "",
                "startTime": "2022-03-07T12:00:00-06:00",
                "endTime": "2022-03-07T13:00:00-06:00",
                "isDaytime": true,
                "temperature": 31,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/snow?size=small",
                "shortForecast": "Slight Chance Light Snow",
                "detailedForecast": ""
            },
            {
                "number": 118,
                "name": "",
                "startTime": "2022-03-07T13:00:00-06:00",
                "endTime": "2022-03-07T14:00:00-06:00",
                "isDaytime": true,
                "temperature": 33,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "N",
                "icon": "https://api.weather.gov/icons/land/day/snow?size=small",
                "shortForecast": "Slight Chance Light Snow",
                "detailedForecast": ""
            },
            {
                "number": 119,
                "name": "",
                "startTime": "2022-03-07T14:00:00-06:00",
                "endTime": "2022-03-07T15:00:00-06:00",
                "isDaytime": true,
                "temperature": 34,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "NW",
                "icon": "https://api.weather.gov/icons/land/day/snow?size=small",
                "shortForecast": "Slight Chance Rain And Snow",
                "detailedForecast": ""
            },
            {
                "number": 120,
                "name": "",
                "startTime": "2022-03-07T15:00:00-06:00",
                "endTime": "2022-03-07T16:00:00-06:00",
                "isDaytime": true,
                "temperature": 35,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "NW",
                "icon": "https://api.weather.gov/icons/land/day/snow?size=small",
                "shortForecast": "Slight Chance Rain And Snow",
                "detailedForecast": ""
            },
            {
                "number": 121,
                "name": "",
                "startTime": "2022-03-07T16:00:00-06:00",
                "endTime": "2022-03-07T17:00:00-06:00",
                "isDaytime": true,
                "temperature": 36,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "NW",
                "icon": "https://api.weather.gov/icons/land/day/snow?size=small",
                "shortForecast": "Slight Chance Rain And Snow",
                "detailedForecast": ""
            },
            {
                "number": 122,
                "name": "",
                "startTime": "2022-03-07T17:00:00-06:00",
                "endTime": "2022-03-07T18:00:00-06:00",
                "isDaytime": true,
                "temperature": 37,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "15 mph",
                "windDirection": "NW",
                "icon": "https://api.weather.gov/icons/land/day/rain?size=small",
                "shortForecast": "Slight Chance Light Rain",
                "detailedForecast": ""
            },
            {
                "number": 123,
                "name": "",
                "startTime": "2022-03-07T18:00:00-06:00",
                "endTime": "2022-03-07T19:00:00-06:00",
                "isDaytime": false,
                "temperature": 36,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "NW",
                "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
                "shortForecast": "Partly Cloudy",
                "detailedForecast": ""
            },
            {
                "number": 124,
                "name": "",
                "startTime": "2022-03-07T19:00:00-06:00",
                "endTime": "2022-03-07T20:00:00-06:00",
                "isDaytime": false,
                "temperature": 34,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "NW",
                "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
                "shortForecast": "Partly Cloudy",
                "detailedForecast": ""
            },
            {
                "number": 125,
                "name": "",
                "startTime": "2022-03-07T20:00:00-06:00",
                "endTime": "2022-03-07T21:00:00-06:00",
                "isDaytime": false,
                "temperature": 31,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "NW",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 126,
                "name": "",
                "startTime": "2022-03-07T21:00:00-06:00",
                "endTime": "2022-03-07T22:00:00-06:00",
                "isDaytime": false,
                "temperature": 28,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "NW",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 127,
                "name": "",
                "startTime": "2022-03-07T22:00:00-06:00",
                "endTime": "2022-03-07T23:00:00-06:00",
                "isDaytime": false,
                "temperature": 26,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "NW",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 128,
                "name": "",
                "startTime": "2022-03-07T23:00:00-06:00",
                "endTime": "2022-03-08T00:00:00-06:00",
                "isDaytime": false,
                "temperature": 25,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "NW",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 129,
                "name": "",
                "startTime": "2022-03-08T00:00:00-06:00",
                "endTime": "2022-03-08T01:00:00-06:00",
                "isDaytime": false,
                "temperature": 24,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "NW",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 130,
                "name": "",
                "startTime": "2022-03-08T01:00:00-06:00",
                "endTime": "2022-03-08T02:00:00-06:00",
                "isDaytime": false,
                "temperature": 23,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "NW",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 131,
                "name": "",
                "startTime": "2022-03-08T02:00:00-06:00",
                "endTime": "2022-03-08T03:00:00-06:00",
                "isDaytime": false,
                "temperature": 22,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "NW",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 132,
                "name": "",
                "startTime": "2022-03-08T03:00:00-06:00",
                "endTime": "2022-03-08T04:00:00-06:00",
                "isDaytime": false,
                "temperature": 21,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "W",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 133,
                "name": "",
                "startTime": "2022-03-08T04:00:00-06:00",
                "endTime": "2022-03-08T05:00:00-06:00",
                "isDaytime": false,
                "temperature": 20,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "W",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 134,
                "name": "",
                "startTime": "2022-03-08T05:00:00-06:00",
                "endTime": "2022-03-08T06:00:00-06:00",
                "isDaytime": false,
                "temperature": 19,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "W",
                "icon": "https://api.weather.gov/icons/land/night/skc?size=small",
                "shortForecast": "Clear",
                "detailedForecast": ""
            },
            {
                "number": 135,
                "name": "",
                "startTime": "2022-03-08T06:00:00-06:00",
                "endTime": "2022-03-08T07:00:00-06:00",
                "isDaytime": true,
                "temperature": 19,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "W",
                "icon": "https://api.weather.gov/icons/land/day/skc?size=small",
                "shortForecast": "Sunny",
                "detailedForecast": ""
            },
            {
                "number": 136,
                "name": "",
                "startTime": "2022-03-08T07:00:00-06:00",
                "endTime": "2022-03-08T08:00:00-06:00",
                "isDaytime": true,
                "temperature": 20,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "W",
                "icon": "https://api.weather.gov/icons/land/day/skc?size=small",
                "shortForecast": "Sunny",
                "detailedForecast": ""
            },
            {
                "number": 137,
                "name": "",
                "startTime": "2022-03-08T08:00:00-06:00",
                "endTime": "2022-03-08T09:00:00-06:00",
                "isDaytime": true,
                "temperature": 23,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "W",
                "icon": "https://api.weather.gov/icons/land/day/skc?size=small",
                "shortForecast": "Sunny",
                "detailedForecast": ""
            },
            {
                "number": 138,
                "name": "",
                "startTime": "2022-03-08T09:00:00-06:00",
                "endTime": "2022-03-08T10:00:00-06:00",
                "isDaytime": true,
                "temperature": 26,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "W",
                "icon": "https://api.weather.gov/icons/land/day/skc?size=small",
                "shortForecast": "Sunny",
                "detailedForecast": ""
            },
            {
                "number": 139,
                "name": "",
                "startTime": "2022-03-08T10:00:00-06:00",
                "endTime": "2022-03-08T11:00:00-06:00",
                "isDaytime": true,
                "temperature": 31,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "W",
                "icon": "https://api.weather.gov/icons/land/day/skc?size=small",
                "shortForecast": "Sunny",
                "detailedForecast": ""
            },
            {
                "number": 140,
                "name": "",
                "startTime": "2022-03-08T11:00:00-06:00",
                "endTime": "2022-03-08T12:00:00-06:00",
                "isDaytime": true,
                "temperature": 36,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "W",
                "icon": "https://api.weather.gov/icons/land/day/skc?size=small",
                "shortForecast": "Sunny",
                "detailedForecast": ""
            },
            {
                "number": 141,
                "name": "",
                "startTime": "2022-03-08T12:00:00-06:00",
                "endTime": "2022-03-08T13:00:00-06:00",
                "isDaytime": true,
                "temperature": 40,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "W",
                "icon": "https://api.weather.gov/icons/land/day/few?size=small",
                "shortForecast": "Sunny",
                "detailedForecast": ""
            },
            {
                "number": 142,
                "name": "",
                "startTime": "2022-03-08T13:00:00-06:00",
                "endTime": "2022-03-08T14:00:00-06:00",
                "isDaytime": true,
                "temperature": 43,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "W",
                "icon": "https://api.weather.gov/icons/land/day/few?size=small",
                "shortForecast": "Sunny",
                "detailedForecast": ""
            },
            {
                "number": 143,
                "name": "",
                "startTime": "2022-03-08T14:00:00-06:00",
                "endTime": "2022-03-08T15:00:00-06:00",
                "isDaytime": true,
                "temperature": 45,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "W",
                "icon": "https://api.weather.gov/icons/land/day/few?size=small",
                "shortForecast": "Sunny",
                "detailedForecast": ""
            },
            {
                "number": 144,
                "name": "",
                "startTime": "2022-03-08T15:00:00-06:00",
                "endTime": "2022-03-08T16:00:00-06:00",
                "isDaytime": true,
                "temperature": 46,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "W",
                "icon": "https://api.weather.gov/icons/land/day/few?size=small",
                "shortForecast": "Sunny",
                "detailedForecast": ""
            },
            {
                "number": 145,
                "name": "",
                "startTime": "2022-03-08T16:00:00-06:00",
                "endTime": "2022-03-08T17:00:00-06:00",
                "isDaytime": true,
                "temperature": 46,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "W",
                "icon": "https://api.weather.gov/icons/land/day/few?size=small",
                "shortForecast": "Sunny",
                "detailedForecast": ""
            },
            {
                "number": 146,
                "name": "",
                "startTime": "2022-03-08T17:00:00-06:00",
                "endTime": "2022-03-08T18:00:00-06:00",
                "isDaytime": true,
                "temperature": 46,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "W",
                "icon": "https://api.weather.gov/icons/land/day/few?size=small",
                "shortForecast": "Sunny",
                "detailedForecast": ""
            },
            {
                "number": 147,
                "name": "",
                "startTime": "2022-03-08T18:00:00-06:00",
                "endTime": "2022-03-08T19:00:00-06:00",
                "isDaytime": false,
                "temperature": 44,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "5 mph",
                "windDirection": "W",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 148,
                "name": "",
                "startTime": "2022-03-08T19:00:00-06:00",
                "endTime": "2022-03-08T20:00:00-06:00",
                "isDaytime": false,
                "temperature": 41,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "5 mph",
                "windDirection": "W",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 149,
                "name": "",
                "startTime": "2022-03-08T20:00:00-06:00",
                "endTime": "2022-03-08T21:00:00-06:00",
                "isDaytime": false,
                "temperature": 38,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "5 mph",
                "windDirection": "SW",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 150,
                "name": "",
                "startTime": "2022-03-08T21:00:00-06:00",
                "endTime": "2022-03-08T22:00:00-06:00",
                "isDaytime": false,
                "temperature": 35,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "5 mph",
                "windDirection": "SW",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 151,
                "name": "",
                "startTime": "2022-03-08T22:00:00-06:00",
                "endTime": "2022-03-08T23:00:00-06:00",
                "isDaytime": false,
                "temperature": 33,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "5 mph",
                "windDirection": "SW",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 152,
                "name": "",
                "startTime": "2022-03-08T23:00:00-06:00",
                "endTime": "2022-03-09T00:00:00-06:00",
                "isDaytime": false,
                "temperature": 32,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "SW",
                "icon": "https://api.weather.gov/icons/land/night/few?size=small",
                "shortForecast": "Mostly Clear",
                "detailedForecast": ""
            },
            {
                "number": 153,
                "name": "",
                "startTime": "2022-03-09T00:00:00-06:00",
                "endTime": "2022-03-09T01:00:00-06:00",
                "isDaytime": false,
                "temperature": 31,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "SW",
                "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
                "shortForecast": "Partly Cloudy",
                "detailedForecast": ""
            },
            {
                "number": 154,
                "name": "",
                "startTime": "2022-03-09T01:00:00-06:00",
                "endTime": "2022-03-09T02:00:00-06:00",
                "isDaytime": false,
                "temperature": 30,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "10 mph",
                "windDirection": "SW",
                "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
                "shortForecast": "Partly Cloudy",
                "detailedForecast": ""
            },
            {
                "number": 155,
                "name": "",
                "startTime": "2022-03-09T02:00:00-06:00",
                "endTime": "2022-03-09T03:00:00-06:00",
                "isDaytime": false,
                "temperature": 28,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "5 mph",
                "windDirection": "SW",
                "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
                "shortForecast": "Partly Cloudy",
                "detailedForecast": ""
            },
            {
                "number": 156,
                "name": "",
                "startTime": "2022-03-09T03:00:00-06:00",
                "endTime": "2022-03-09T04:00:00-06:00",
                "isDaytime": false,
                "temperature": 27,
                "temperatureUnit": "F",
                "temperatureTrend": null,
                "windSpeed": "5 mph",
                "windDirection": "SW",
                "icon": "https://api.weather.gov/icons/land/night/sct?size=small",
                "shortForecast": "Partly Cloudy",
                "detailedForecast": ""
            }
        ]
    }
}    
""".trimIndent()